### ISSUE TITLE
KAMPANAT THUMWONG

### ISSUE THREAD

**Issue by abc1000200** [MicrosoftDocs/windows-dev-docs#4866]
### Type of issue

Typo

### Feedback

TK

### Page URL

https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/create-app-store-listing?pivots=store-installer-msi-exe

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/publish-your-app/create-app-store-listing.md

### Author

@GrantMeStrength

### Document Id

07dc5582-999a-a880-1a02-986dc11e2152

**Comment by mattwojo** [comment]
Doesn't appear to be any actual issue identified here. Please reopen if you would like to specify the issue that you've found.
