### ISSUE TITLE
IHeyReally 

### ISSUE THREAD

**Issue by Heyitsquoracom** [MicrosoftDocs/windows-dev-docs#4912]
### Type of issue

Typo

### Feedback

<script type="module" src="https://get.microsoft.com/badge/ms-store-badge.bundled.js"></script>
<ms-store-badge
	productid="9n4tfbzk2c7s"
	window-mode="pop up"
	theme="dark"
	language="en-us"
	animation="off">
</ms-store-badge>

### Page URL

https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/overview

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/publish-your-app/overview.md

### Author

@GrantMeStrength

### Document Id

06f54870-f12b-d72f-3899-a188bba87627

**Comment by GrantMeStrength** [comment]
Could you provide some more information regarding the typo, please? I can't see it.

**Comment by GrantMeStrength** [comment]
Hopefully typo was fixed.
