### ISSUE TITLE
IHeyReally 

### ISSUE THREAD

**Issue by Heyitsquoracom** [MicrosoftDocs/windows-dev-docs#4913]
### Type of issue

Typo

### Feedback

<script type="module" src="https://get.microsoft.com/badge/ms-store-badge.bundled.js"></script>
<ms-store-badge
	productid="9n4tfbzk2c7s"
	window-mode="pop up"
	theme="dark"
	language="en-us"
	animation="off">
</ms-store-badge>

### Page URL

https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/schedule-pricing-changes

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/publish-your-app/schedule-pricing-changes.md

### Author

@GrantMeStrength

### Document Id

3d9675bd-5ea7-5cee-7334-b406ddcb5518

**Comment by GrantMeStrength** [comment]
Could you mention the exact typo, thanks!

**Comment by GrantMeStrength** [comment]
Hopefully the typo was fixed.
